name: ToggleHardcore
version: '${version}'
authors: [Allison]
main: tech.allydoes.togglehardcore.ToggleHardcore
depend: ["Geyser-Spigot"]
api-version: '1.21'
commands:
  toggleHardcore:
    description: Toggle hardcore mode
    usage: /toggleHardcore
    permission: ToggleHardcore.toggleHardcore
  hardcore:
    description: Admin command for managing players' hardcore mode
    usage: /hardcore
    permission: ToggleHardcore.admin
  dayCounter:
    description: Gets the amount of in-game days that you've being alive
    usage: /daycounter
    permission: ToggleHardcore.dayCounter